---
title: "Data Visualistation Story Telling"
author: "Vincent Krieg"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Republicans don't believe in climate change so those states will use less renewable Energies


```{r}
library(readr)
library(tidyverse)
library(usmap)
library(ggplot2)
library(yhat)
library(gridExtra)
library(grid)
```

### Import of the Data ###

```{r}
totalData <- read_csv("totalData.csv")
```
```{r}
# Download data and store in project directory
mapDemRep <- totalData %>% filter(YEAR=="2020") %>% filter(Type_of_Producer=='Total Electric Power Industry') %>% mutate(dem_rep=if_else(dem_percent>rep_percent,"Democratic","Republican"))
cols <- c("Republican" = "red", "Democratic" = "blue")
USplot <-  plot_usmap(data = mapDemRep, values="dem_rep",regions = "states",labels = TRUE) + 
 scale_fill_manual(values = cols, name = "Political Party", 
                  guide = guide_legend(reverse = TRUE))+
    labs(title = "Pesidential elections in the US 2020") +
  theme(legend.position = "bottom")
  
USplot$layers[[2]]$aes_params$size <- 2



```
```{r}
greenCard <- totalData %>% filter(YEAR=="2020") %>% filter(Type_of_Producer=='Total Electric Power Industry')  %>% mutate(renewableTotal=HydroElectric+Wind+wood+biomass+Geothermal+Solar) %>% mutate(renewablePercent= (renewableTotal/Total)*100)

USplot1 <-  plot_usmap(data =greenCard, values="renewablePercent",regions = "states",labels = TRUE) + 
    scale_fill_continuous(low = "white", high = "green", name = "Renewable Energy in %", label = scales::comma)+
    labs(
       title = "Percentage of renewable energy used by state 2020") +
  theme(legend.position = "bottom")
  
USplot1$layers[[2]]$aes_params$size <- 2


grid.arrange(USplot,USplot1, ncol=2, top=textGrob("Politics and renewable energies in the United States",gp=gpar(fontsize=20,font=3)))


```
```{r}
greenCard <- greenCard %>% 
  mutate(coalPercent= (Coal/Total)*100) %>%
  mutate(HydroElectricPercent= (HydroElectric/Total)*100) %>%
  mutate(gasPercent= (Gas/Total)*100) %>%
  mutate(petroleumPercent= (Petroleum/Total)*100) %>%
  mutate(windPercent= (Wind/Total)*100) %>%
  mutate(woodPercent= (wood/Total)*100) %>%
  mutate(nuclearPercent= (Nuclear/Total)*100) %>%
  mutate(biomassPercent= (biomass/Total)*100) %>%
  mutate(geothermalPercent= (Geothermal/Total)*100) %>%
  mutate(solarPercent= (Solar/Total)*100)


```

```{r}

createUSmap <- function(colName,colorPlot, nameScale, titlePlot){
  returnPlot <-  plot_usmap(data =greenCard, values=colName,regions = "states",labels = TRUE) + 
    scale_fill_continuous(low = "white", high = colorPlot, 
                          name = nameScale, label = scales::comma)+
    labs(title = titlePlot) +
  theme(legend.position = "bottom")
  returnPlot$layers[[2]]$aes_params$size <- 2
  return(returnPlot)
}

  

coal <- createUSmap("coalPercent","black","Percentage coal in energymix", "Coal")
hydro <- createUSmap("HydroElectricPercent","darkblue","Percentage hydro electric in energymix", "Hydro Electic")
gas <- createUSmap("gasPercent","brown","Percentage natural gas in energymix", "Natural Gas")
petr <- createUSmap("petroleumPercent","darkgrey","Percentage petroleum in energymix", "Petroleum")
wind <- createUSmap("windPercent","lightblue","Percentage wind in energymix", "Wind")
nuc <- createUSmap("nuclearPercent","green","Percentage nuclear in energymix", "Nuclear")
bio <- createUSmap("biomassPercent","brown","Percentage biomass in energymix", "Biomass")
geo <- createUSmap("geothermalPercent","darkred","Percentage geothermal in energymix", "Geothermal")
solar <- createUSmap("solarPercent","yellow","Percentage solar in energymix", "Solar")
wood <- createUSmap("woodPercent","darkgreen","Percentage wood in energymix", "Wood")

```


```{r}


#grid.arrange(coal,USplot1,hydro,gas,petr,wind,nuc,bio,geo,solar,wood, ncol=2,nrow=6, top=textGrob("Politics and renewable energies in the United States",gp=gpar(fontsize=20,font=3)))
grid.arrange(bio,wood,geo,nuc, ncol=2,nrow=2, top=textGrob("Politics and renewable energies in the United States",gp=gpar(fontsize=20,font=3)))

```

```{r}



```



```{r}


#Check for the logarithmic functions used in the Regression
greenCard <- greenCard[!(greenCard$state == "US-Total"),]
greenCard <- greenCard[!(greenCard$state == "DC"),]

greenCard <- greenCard %>% mutate(renewablePercent = log(renewablePercent)) 

CorrelationPlots <- pivot_longer(greenCard,cols = c("SunHours", "AvgWindSpeed", "Population", "EducationIndex", "rep_percent", "GdpinMioUSD"), names_to = "VarName", values_to = "VarValues")

p <- ggplot(CorrelationPlots, mapping = aes(VarValues, renewablePercent)) + 
  geom_point()+
  geom_smooth(method='lm')
p + facet_wrap(~VarName, scales = "free_x", ncol = 3, labeller = labeller(VarName =
                                                                            c("SunHours" = "Average sunshine hours per day", 
                                                                              "AvgWindSpeed" = "Average Wind Speed", 
                                                                              "Population"= "Population", 
                                                                              "EducationIndex"="Education index", 
                                                                              "rep_percent" = "Percentage votes Republicans 2020 ",
                                                                              "GdpinMioUSD" = "Gdp in Mio USD in 2020")
                                                                          ))+
  ylab("Log percentage of renewable energy")+
  xlab("Individual units")+
  labs(title = "Correlation of individual factors on the percentage of renewable energy used" )+
  theme(panel.spacing = unit(2, "lines"))

```
```{r}

lmodel <- lm(renewablePercent ~ SunHours + AvgWindSpeed + Population + EducationIndex + GdpinMioUSD + rep_percent, data = greenCard)
summary(lmodel)

```
```{r}
greenCard <- data.frame(greenCard, y_hat = fitted(lmodel), e = residuals(lmodel))
print(greenCard)
```
```{r}
greenCard %>% ggplot(mapping = aes(renewablePercent, y_hat))+
  geom_point(color = "steelblue")+
  geom_line(data = greenCard,mapping= aes(renewablePercent, renewablePercent), color = "darkred")+
  ylab("predicted log renewable energy percent")+
  xlab("actual log renewable energy percent")+
  theme_bw()

```

```{r}
barPlotData <- totalData %>% 
  mutate(coalPercent= (Coal/Total)*100) %>%
  mutate(HydroElectricPercent= (HydroElectric/Total)*100) %>%
  mutate(gasPercent= (Gas/Total)*100) %>%
  mutate(petroleumPercent= (Petroleum/Total)*100) %>%
  mutate(windPercent= (Wind/Total)*100) %>%
  mutate(woodPercent= (wood/Total)*100) %>%
  mutate(nuclearPercent= (Nuclear/Total)*100) %>%
  mutate(biomassPercent= (biomass/Total)*100) %>%
  mutate(geothermalPercent= (Geothermal/Total)*100) %>%
  mutate(solarPercent= (Solar/Total)*100) %>% filter(YEAR == 2020) %>% filter(state == "US-Total") %>% filter(Type_of_Producer =="Total Electric Power Industry")
barPlotData <- pivot_longer(barPlotData,cols = c("coalPercent", "HydroElectricPercent", "gasPercent", "petroleumPercent", "windPercent", "nuclearPercent","biomassPercent","geothermalPercent","solarPercent"), names_to = "VarName", values_to = "VarValues")
barPlotData <- barPlotData[order(-barPlotData$VarValues),]

```
```{r}
barPlotData %>% ggplot(mapping = aes(fct_reorder(VarName,
                         VarValues, .desc = TRUE), 
             VarValues)) +
  geom_col(color = VarName)+
  ylab("Percentage in the US energymix")#+
  #scale_fill_manual(values = c(rep(c("gray45", "gray75"))))
  #theme(axis.title.x=element_blank(),
    #    axis.text.x=element_blank(),
     #   axis.ticks.x=element_blank())

```
```{r}


```









Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
